package projpesoideal;//CRIAÇÃO DO PACOTE "projpesoideal", AQUI ESTÃO CONTIDAS TODAS AS CLASSES DO PROJETO
//LINHA EM BRANCO IGNORADA PELO PROGRAMA
public class Pessoa {//CRIAÇÃO DA CLASSE PESSOA, NELA ESTÃO CONTIDAS TODOS OS MÉTODOS DOS OBJETOS QUE SERÃO CRIADOS
    private double altura;//DECLARAÇÃO DA VARIÁVEL ALTURA, DO TIPO DOUBLE PORQUE É NÚMERO COM VÍRGULA E PRIVADO PARA QUE APENAS ESTA CLASSE TENHA ACESSO DIRETO
    private byte sexo;//DECLARAÇÃO DA VARIÁVEL SEXO, DO TIPO BYTE PORQUE É UM NÚMERO PEQUENO E PRIVADO PARA QUE APENAS ESTA CLASSE TENHA ACESSO DIRETO
    private double pesoAtual;//DECLARAÇÃO DA VARIÁVEL PESO ATUAL, DO TIPO DOUBLE PORQUE É UM NÚMERO COM VÍRGULA E PRIVADO PARA QUE APENAS ESTA CLASSE TENHA ACESSO A ELA
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public double getAltura() {//CRIAÇÃO DO MÉTODO getAltura, DO TIPO DOUBLE PORQUE RETORNA A ALTURA DO OBJETO, E SEM PARÂMETROS PORQUE APENAS RETORNA O VALOR
        return altura;//RETORN DA ALTURA
    }//FIM DO MÉTODO getAltura
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public void setAltura(double altura) {//CRIAÇÃO DO MÉTODO setAltura, DO TIPO VOID PORQUE NÃO RETORNA NADA, COM PARÂMETROS PORQUE RECEBE DADOS DE FORA DA CLASSE
        this.altura = altura;//ATRIBUIÇÃO DO VALOR RECEBIDO DA CLASSE MAIN, PARA A CLASSE PESSOA
    }//FIM DO MÉTODO setAltura
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public byte getSexo() {//CRIAÇÃO DO MÉTODO getSexo, DO TIPO BYTE PORQUE RETORNA O SEXO DO OBJETO, E SEM PARÂMETROS PORQUE APENAS RETORNA O VALOR
        return sexo;//RETORNO DO SEXO
    }//FIM DO MÉTODO getSexo
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public void setSexo(byte sexo) {//CRIAÇÃO DO MÉTODO setSexo, DO TIPO VOID PORQUE NÃO RETORNA NADA, COM PARÂMETROS PORQUE RECEBE DADOS DE FORA DA CLASSE
        this.sexo = sexo;//ATRIBUIÇÃO DO VALOR RECEBIDO DA CLASSE MAIN, PARA A CLASSE PESSOA
    }//FIM DO MÉTODO setSexo
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public double getPesoAtual() {//CRIAÇÃO DO MÉTODO getPesoaAtal, DO TIPO DOUBLE PORQUE RETORNA O PESO ATUAL DO OBJETO, E SEM PARÂMETROS PORQUE APENAS RETORNA O VALOR
        return pesoAtual;//RETORNO DO PESO ATUAL
    }//FIM DO MÉTODO getPesoAtual
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public void setPesoAtual(double pesoAtual) {//CRIAÇÃO DO MÉTODO setPesoAtual, DO TIPO VOID PORQUE NÃO RETORNA NADA, COM PARÂMETROS PORQUE RECEBE DADOS DE FORA DA CLASSE
        this.pesoAtual = pesoAtual;//ATRIBUIÇÃO DO VALOR RECEBIDO DA CLASSE MAIN, PARA A CLASSE PESSOA
    }//FIM DO MÉTODO setPesoAtual
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA    
    public double calcularPesoIdeal(){//CRIAÇÃO DO MÉTODO calcularPesoIdeal, DO TIPO DOUBLE PORQUE VAI RETORNAR UM VALOR VÍRGULA, SEM PARÂMETROS PORQUE É DE RETORNO
        if(this.sexo==1){//SE O SEXO FOR IGUAL 1, ENTÃO, SEGUNDO A LEGENDA DA CLASSE MAIN, SERÁ CALCULADO O PESO SE A PESSOA FOR DO SEXO MASCULINO
            return (72.7*this.altura)-58;//RETORNA O VALOR DO PESO IDEAL SE A PESSOA FOR HOMEM
        }//FIM DA ESTRUTURA CONDICIONAL 
         return (62.1*this.altura)-44.7;//RETORNA O VALOR DO PESO IDEAL SE A PESSOA FOR MULHERE
    }//FIM DO MÉTODO calcularPesoIdeal
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public String verificarPeso(){//CRIAÇÃO DO MÉTODO verificarPeso, ELE VAI RETORNAR UMA STRING DIZENDO SE A PESSOA ESTÁ ACIMA DO PESO, NO PESO ATUAL OU ACIMA DO PESO
        if(this.pesoAtual<this.calcularPesoIdeal()-2){//SE O PESO ATUAL DA PESSOA FOR MENOR QUE QUE O PESO IDEAL MENOS 2, A LINHA ABAIXO SERÁ EXECUTADA
            return "ABAIXO DO PESO";//RETORNO CASO A PESSOA ESTEJA ABAIXO DO PESO
        }else if(this.pesoAtual>this.calcularPesoIdeal()+2){//SE O PESO ATUAL DA PESSOA FOR MAIOR QUE O PESO IDEAL MAIS 2, A LINHA ABAIXO SERÁ EXECUTADA
            return "ACIMA DO PESO";//RETORNO CASO A PESSOA ESTEJA ACIMA DO PESO
        }//FIM DA ESTRUTURA CONDICIONAL
        return "NO PESO IDEAL";//RETORNO CASO A PESSOA ESTEJA NO SEU PESO IDEAL
    }//FIM DO MÉTODO verificarPeso
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    @Override//DOCUMENTAÇÃO JAVA
    public String toString() {//CRIAÇÃO DO MÉTODO toString, QUE É USADO PARA MOSTRAR NA TELA OS OBJETOS E SEUS ATRIBUTOS
        return "\n\nINFORMAÇÕES DA PESSOA\n"//LEGENDA PARA INFORMAR QUE SERÃO MOSTRADOS OS DADOS DA PESSOA
                + "Altura: " + altura +"\n"//INFORMA A ALTURA
                + "Sexo: " + sexo +"\n"//INFORMA O PESO
                + "Peso atual: " + pesoAtual;//INGORMA O PESO ATUAL
    }//FIM DO MÉTODO toString
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA    
}//FIM DA CLASSE PESSOA
