package projvendedor;//CRIAÇÃO DO PACOTE "projvendedor", NELE VÃO CONTER TODAS AS CLASSES CRIADAS NO PROJETO
//LINHA EM BRANCO IGNORADA PELO PROGRAMA
import java.util.Scanner;//IMPORTAÇÃO DA CLASSE SCANNER, PARA QUE O USUÁRIO POSSA INTERAGIR COM O PROGRAMA
//LINHA EM BRANCO IGNORADA PELO PROGRAMA
public class Main {//CRIAÇÃO DA CLASSE MAIN, ONDE VAI ESTAR O MÉTODO main, O QUE TORNA ESTA A CLASSE PRINCIPAL
//LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public static void main(String[] args) {//CRIAÇÃO DO MÉTODO main, QUE É O PRINCIPAL MÉTODO, TUDO O QUE TIVER DENTRO DELE SERÁ EXECUTADO
        Scanner leia = new Scanner(System.in);//INSTANCIAMENTO DA CLASSE SCANNER, OU SEJA, ESSA LINHA CRIA O OBJETO "leia" PARA A CLASSE "Scanner" PARA QUE POSSAMOS USAR O MÉTODO "next" E FAZER COM QUE O USUÁRIO INTERAJA
        Vendedor objVendedor = new Vendedor();//INSTANCIMANETO DA CLASSE VENDEDOR, PARA QUE POSSAMOS USAR OS MÉTODOS NELA CONTIDOS
        //LINHA EM BRANCO IGNORADA PELO PROGRAMA        
        float valorVendido;//DECLARAÇÃO DA VARIÁVEL valorVendido, DO TIPO float PORQUE CONTÉM PONTO FLUTUANTE
        //LINHA EM BRANCO IGNORADA PELO PROGRAMA
        System.out.println("INSIRA OS DADOS DO VENDEDOR");//LEGENDA PARA INFORMAR AO USUÁRIO QUE ELE PRECISA INTERAGIR COM O PROGRAMA
        System.out.print("Nome: ");//LEGENDA PARA INFORMAR AO USUÁRIO QUE PRECISA DIGITAR O NOME
        objVendedor.setNome(leia.next());//AQUI O NOME É LIDO, E ATRAVÉS DO MÉTODO set, JOGA O NOME DO VENDEDOR PARA A CLASSE VENDEDOR
        System.out.print("Meta: R$ ");//LEGENDA PARA INFORMAR AO USUÁRIO QUE PRECISA DIGITAR SUA META
        objVendedor.setMeta(leia.nextFloat());//AQUI A META É LIDA E ATRAVÉS DO MÉTODO set, JOGA A META PARA A CLASSE VENDEDOR
        System.out.print("Total vendido: R$ ");//LEGENDA PARA INFORMAR AO USUÁRIO QUE PRECISA DIGITAR O TOTAL VENDIDO
        valorVendido = leia.nextFloat();//AQUI O TOTAL VENDIDO É LIDO E COLOCADO NA VARIÁVEL
        //LINHA EM BRANCO IGNORADA PELO PROGRAMA
        System.out.println(objVendedor+"\n"//AQUI SERÃO INFORMADOS OS DADOS DO VENDEDOR
                + "VALOR DA COMISSÃO: R$ "+objVendedor.calcularComissao(valorVendido));//ESSE MÉTODO CALCULA A COMISSÃO DO VENDEDOR EJOGA NA TELA
    }//FIM DO MÉTODO main
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
}//FIM DA CLASSE MAIN
