package projvendedor;//CRIAÇÃO DO PACOTE "projvendedor", NELE VÃO CONTER TODAS AS CLASSES CRIADAS NO PROJETO
//LINHA EM BRANCO IGNORADA PELO PROGRAMA
public class Vendedor {//CRIAÇÃO DA CLASSE VENDEDOR, NELA ESTÃO CONTIDAS TODOS OS MÉTODOS DOS OBJETOS QUE SERÃO CRIADOS
    private String nome;//DECLARAÇÃO DA VARIÁVEL NOME, DE FORMA PRIVADA PARA QUE APENAS ESTA CLASSE TENHA ACESSO DIRETO A ELA, DO TIPO STRING PORQUE É UM TEXTO
    private float meta;//DECLARAÇÃO DA VARIÁVEL META, DE FORMA PRIVADA PARA QUE APENAS ESTA CLASSE TENHA ACESSO DIRETO À ELA, DO TIPO FLOAT PORQUE CONTÉM VÍRGULA
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public String getNome() {//CRIAÇÃO DO MÉTODO getNome, ELE RETORNA O NOME DO OBJETO VENDEDOR, DE FORMA PÚBLICA PARA QUE AS OUTRAS CLASSES TENHAM ACESSO À ESTE MÉTODO
        return nome;//RETORNO DO NOME
    }//FIM DO MÉTODO getNome
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public void setNome(String nome) {//CRIAÇÃO DO MÉTODO setNome, ELE RECEBE O VALOR DA CLASSE Main, E ATRIBUI O VALOR PARA A VARIÁVEL DESSA CLASSE, COM PARÂMETRO PORQUE RECEBE VALOR DE OUTRA CLASSE, DO TIPO void PORQUE NÃO RETORNA NADA
        this.nome = nome;//ATRIBUIÇÃO DO NOME DA CLASSE Main PARA ESTA CLASSE
    }//FIM DO MÉTODO setNome
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public float getMeta() {//CRIAÇÃO DO MÉTODO getMeta, ELE RETORNA A META DO OBJETO VENDEDOR, DE FORMA PÚBLICA PARA QUE AS OUTRAS CLASSES TENHAM ACESSO À ESTE MÉTODO
        return meta;//RETORNO DA META
    }//FIM DO MÉTODO getMeta
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public void setMeta(float meta) {//CRIAÇÃO DO MÉTODO setMeta, ELE RECEBE O VALOR DA CLASSE Main, E ATRIBUI O VALOR PARA A VARIÁVEL DESSA CLASSE, COM PARÂMETRO PORQUE RECEBE VALOR DE OUTRA CLASSE, DO TIPO void PORQUE NÃO RETORNA NADA
        this.meta = meta;//ATRIBUIÇÃO DA META DA CLASSE Main PARA ESTA CLASSE
    }//FIM DO MÉTODO setMeta
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    public double calcularComissao(float valorVendido){//CRIAÇÃO DO MÉTODO calcularComissao, COM PARÂMETRO PORQUE RECEBE VALOR DE OUTRA CLASSE, DO TIPO double PORQUE ELE RETORNA UM VALOR COM VÍRGULA, PARA CALCULAR A COMISSÃO DO VENDEDOR
        if(valorVendido<this.meta*0.5){//SE O VALOR VENDIDO FOR MENOR QUE 50% DA META, ESSA CONDIÇÃO É VERDADEIRA, A LINHA ABAIXO SERÁ EXECUTADA
            return valorVendido*0.01;//RETURNA 1% DO VALOR DAS VENDAS
        }else if(valorVendido<this.meta*0.75){//SE O VALOR VENDIDO FOR MENOR QUE 75% DA META, ESSA CONDIÇÃO É VERDADEIRA, A LINHA ABAIXO SERÁ EXECUTADA
            return valorVendido*0.025;//RETORNA 2,5% DO VALOR DAS VENDAS
        }else if(valorVendido<=this.meta){//SE O VALOR VENDIDO FOR MENOR QUE O VALOR DA META, ESSA CONDIÇÃO É VERDADEIRA, E A LINHA ABAIXO SERÁ EXECUTADA
            return valorVendido*0.035;//RETORNA 3,5% DO VALOR DAS VENDAS
        }//FIM DA ESTRUTURA CONDICIONAL
        //LINHA EM BRANCO IGNORADA PELO PROGRAMA
        return valorVendido*0.05;//RETORNA 5% DO VALOR DAS VENDAS
    }//FIM DO MÉTODO calcularComissao
    //LINHA EM BRANCO IGNORADA PELO PROGRAMA
    @Override//DOCUMENTAÇÃO JAVA
    public String toString() {//CRIAÇÃO DO MÉTODO toString, ELE RETORNA TODOS OS ATRIBUTOS DOS OBJETOS CRIADOS
        return "\n\nINFORMAÇÕES DO VENDEDOR\n"//LEGENDA QUE DIZ QUE SERÃO INFORMADOS OS DADOS DO VENDEDOR
                + "Nome: " + nome +"\n"//MOSTRA O NOME DO VENDEDOR
                + "Meta: R$ " + meta;//MOSTRA A META DO VENDEDOR
    }//FIM DO MÉTODO toString
     //LINHA EM BRANCO IGNORADA PELO PROGRAMA
}//FIM DA CLASSE PESSOA
